import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

test("home is a centered title with feature buttons", async () => {
  const source = await readFile(new URL("../src/MarketingPages.tsx", import.meta.url), "utf8");
  const css = await readFile(new URL("../src/marketing.css", import.meta.url), "utf8");
  const repo = await readFile(new URL("../src/repo.ts", import.meta.url), "utf8");
  assert.match(source, /mkt-splash/);
  assert.match(source, /mkt-hyphen/);
  assert.match(source, /is-studio/);
  assert.match(source, /mkt-cube/);
  assert.match(source, /mkt-cube-shell/);
  assert.match(source, /mkt-cube-rig/);
  assert.match(source, /rotateY\(\$\{yaw\}deg\)/);
  assert.match(source, /is-facing/);
  assert.match(source, /is-away/);
  assert.match(source, /towardYaw/);
  assert.match(source, /raw > 180 \? raw - 360 : raw/);
  assert.match(source, /WordCube/);
  assert.match(css, /mktEdgeGlint/);
  assert.match(css, /perspective: 42rem/);
  assert.match(css, /\.mkt-cube-rig/);
  assert.match(css, /mktCubeDrift/);
  assert.match(css, /\.mkt-cube-core\.is-away/);
  assert.match(css, /position: fixed/);
  assert.doesNotMatch(css, /rotateY\(20deg\)/);
  assert.match(source, /--mkt-pace/);
  assert.match(source, /readyState/);
  assert.match(source, /paceRef/);
  assert.match(source, /seedStars/);
  assert.match(source, /0\.34/);
  assert.match(source, /0\.66/);
  assert.doesNotMatch(source, /mkt-splash-brand/);
  assert.doesNotMatch(css, /mkt-splash-brand/);
  assert.match(css, /\.mkt-splash-lede \{/);
  assert.doesNotMatch(source, /mkt-cube-home/);
  assert.match(source, /F-Motion/);
  assert.match(source, /aria-label="Features"/);
  assert.match(source, /"Home"/);
  assert.match(source, /"Studio"/);
  assert.match(source, /\/how-it-works/);
  assert.match(source, />GitHub</);
  assert.match(source, /skills\/fmotion/);
  assert.match(source, /\/self-host/);
  assert.match(repo, /ivanillka\/f-motion/);
  assert.match(repo, /advisor\/133-design-contract/);
  assert.doesNotMatch(source, />Hosted</);
  assert.doesNotMatch(source, /href="\/hosted"/);
  assert.doesNotMatch(source, /mkt-hero-media|mkt-recipes|\bComingSoon\b/);
});

test("every marketing page stays on the splash and animates the swap", async () => {
  const pages = await readFile(new URL("../src/MarketingPages.tsx", import.meta.url), "utf8");
  const site = await readFile(new URL("../src/site.tsx", import.meta.url), "utf8");
  assert.match(pages, /How it works/);
  assert.match(pages, /Coming soon on f-motion\.com/);
  assert.match(pages, /FACE_YAW/);
  assert.match(pages, /goFace/);
  assert.match(pages, /ArrowRight/);
  assert.match(pages, /prefers-reduced-motion/);
  assert.match(site, /isMarketingPath/);
  assert.match(site, /history\.pushState/);
  assert.match(site, /document\.addEventListener\("click"/);
  assert.match(site, /path === "\/hosted" \? "\/"/);
});

test("site router keeps self-host on studio-only App", async () => {
  const source = await readFile(new URL("../src/site.tsx", import.meta.url), "utf8");
  assert.match(source, /VITE_SELFHOST_AUTH === "1"/);
  assert.match(source, /studioComingSoon/);
  assert.match(source, /MarketingSite path="\/login"/);
});
